POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
    "id": 5,
    "titulo": "Aprende Node.JS",
    "lenguaje": "javascript",
    "vistas": 45676,
    "nivel": "basico"
}

###

PUT http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
  "id": 2,
  "titulo": "Python intermedio con proyectos",
  "lenguaje": "python",
  "vistas": 123996,
  "nivel": "intermedio"
}

###

PATCH http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
  "titulo": "Python intemedio con proyecto",
  "vistas": 123
}

###

DELETE http://localhost:3000/api/cursos/programacion/1 HTTP/1.1
